repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4 # Use the latest stable version
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: ruff check
        language: python
        args: [--fix ]
        types: [python]
      - id: ruff-format  # New hook for formatting

  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.1.0  # Replace with the correct tag/version
    hooks:
      - id: commitlint
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: check-env-synced
        name: Check .env and .env_example synchronization
        entry: bash app/scripts/check_env_sync.sh
        language: script
        always_run: true
        stages: [pre-commit]
